#! /usr/bin/env bash
#
# Execute a test program built with the Testo library.
#
# The name of this script can be whatever you like. Popular names
# include 'test' and 'testo'.
#
# Run the compiled test program with the original arguments.
# Dune will build it if needed (can be disabled with '--no-build').
# The working directory is the one containing this script.
# All arguments are forwarded to the test binary.
dune exec tests/test.exe -- "$@" --chdir "$(dirname "${BASH_SOURCE[0]}")"
