#! /usr/bin/env bash
#
# The basic test suite for Testo
#
# This script is invoked from meta-test.
# It doesn't invoke dune so as to avoid a warning from dune telling us
# we're already running dune when invoking ./test from meta-test via
# 'dune runtest'.
#
# Regular users should use what's in 'template/test'.

here=$(dirname "${BASH_SOURCE[0]}")
_build/default/tests/test.exe "$@" --chdir "$here"
