#! /usr/bin/env bash
#
# Setup script for building and testing the project.
# Assumes opam is installed.
#
set -eu

eval "$(opam env)"
opam update

# This should not install 'testo' even though it's a dependency of 'testo-lwt'.
opam install --deps-only -y \
  ./testo.opam \
  ./testo-lwt.opam
