#! /usr/bin/env bash
#
# Install system packages required to build and test testo (Ubuntu)
#
# This is used by the CI build.
#
set -eu

sudo apt-get update
sudo apt-get install -y pre-commit

###### Sanity checks ######

echo 'check opam'
opam --version

echo 'check ocamlopt'
opam exec -- ocamlopt -version
