#! /usr/bin/env bash
#
# Setup script for building and testing the project.
# Assumes opam is installed.
#
set -eu

eval "$(opam env)"
opam update

# This should not install 'testo' even though it's a dependency of 'testo-lwt'.
# Pass '-y' to 'setup' to answer 'yes' to all questions from opam.
#
opam install --deps-only "$@" \
  ./testo-diff.opam \
  ./testo-util.opam \
  ./testo.opam \
  ./testo-lwt.opam \
  ocamlformat

# Install pre-commit hooks. See https://pre-commit.com/
pre-commit install
