#! /usr/bin/env bash
#
# Setup script for installing dependencies for Alpine Linux.
#
set -eu

# Use pipx instead of pip to avoid "error: externally-managed-environment"
sudo apk add pipx
pipx install pre-commit

# hmmm
src=$HOME/.local/bin/pre-commit
sudo ln -s "$src" /usr/local/bin/
